### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by commadelimited** [cmeiklejohn/ember-visualizations#3]
This would be a really valuable resource if it was updated to reflect the current state of Ember.

**Comment by cmeiklejohn** [comment]
I'm actively using this in production on an Ember RC application, and will upgrade it as soon as I have a cause to.  Unfortunately I do not have the cycles to upgrade it myself at this point.  That being said, I'd love for someone to submit patches to help get it in line with the latest version of Ember.  I'd be happy to pitch in as time allows.

**Comment by commadelimited** [comment]
Right on! I'm working on an integration with NVd3 right now, but would be nice to remove abstracts and go straight to D3.

**Comment by cmeiklejohn** [comment]
Agreed; I think the best solution is d3 directly.

**Comment by cmeiklejohn** [comment]
I unfortunately am working in a completely different field doing my Ph.D. on distributed computation, so no, I do not have time to maintain this.
